default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: nitanshu

development:

  database: my_app_development

development:
  <<: *default
  database: smart_travel_dev

test:
  <<: *default
  database: smart_travel_test
